---
# Prevents the creation of any AWS resources such as S3 buckets and KMS keys
safe_mode: True

aws:
  assume_role: full-admin
  assume_role_duration: 43200
  region: ap-southeast-2
  profile: chris

s3:
  bucket: chrisdlangton-backup
  base_path: "{{ HOSTNAME }}/{{ USER }}"
  sse: 'aws:kms'
  kms_key_id: alias/s4tool-cli

files:
  - path: '{{ HOME }}/Documents'
    extra_options:
      - '--no-progress'
      - '--acl'
      - 'bucket-owner-full-control'
  - path: '{{ HOME }}/Pictures'
    extra_options:
      - '--no-progress'
      - '--acl'
      - 'bucket-owner-full-control'
# Special settings used when safe_mode False at setup time
setup:
  enable_key_rotation: True
  key_origin: AWS_KMS

  bucket_policy:
    Version: '2012-10-17'
    Id: PutObjPolicy
    Statement:
      - Sid: DenyUnEncryptedObjectUploads
        Effect: Deny
        Principal: "*"
        Action: s3:PutObject
        Resource: arn:aws:s3:::chrisdlangton-backup/*
        Condition:
          StringNotEquals:
            s3:x-amz-server-side-encryption: aws:kms
      - Sid: DenyPlaintextRequests
        Effect: Deny
        Principal:
          AWS: "*"
        Action: s3:*
        Resource: arn:aws:s3:::chrisdlangton-backup/*
        Condition:
          Bool:
            aws:SecureTransport: 'false'

  key_policy:
    Version: '2012-10-17'
    Id: s4tool-keypolicy
    Statement:
      - Sid: Enable IAM User Permissions
        Effect: Allow
        Principal:
          AWS: arn:aws:iam::112398043980:root
        Action: kms:*
        Resource: "*"
      - Sid: Allow access for Key Administrators
        Effect: Allow
        Principal:
          AWS:
            - arn:aws:iam::112398043980:user/chris
            - arn:aws:iam::112398043980:role/full-admin
        Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:TagResource
          - kms:UntagResource
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
        Resource: "*"
      - Sid: Allow use of the key
        Effect: Allow
        Principal:
          AWS:
            - arn:aws:iam::112398043980:user/chris
            - arn:aws:iam::112398043980:role/full-admin
            - arn:aws:iam::112398043980:root
        Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
        Resource: "*"
      - Sid: Allow attachment of persistent resources
        Effect: Allow
        Principal:
          AWS:
            - arn:aws:iam::112398043980:user/chris
            - arn:aws:iam::112398043980:role/full-admin
            - arn:aws:iam::112398043980:root
        Action:
          - kms:CreateGrant
          - kms:ListGrants
          - kms:RevokeGrant
        Resource: "*"
        Condition:
          Bool:
            kms:GrantIsForAWSResource: 'true'
