aws:
  assume_role: full-admin
  region: ap-southeast-2
  access_key_id: ABCDEF123ABCDEF123
  secret_access_key: abcdefabcdefabcdefabcdefabcdefabcdef
kms:
  alias: s4tool
s3:
  bucket: chrisdlangton
  base_path: "{{ HOSTNAME }}/{{ USER }}"    
