aws:
  assume_role: full-admin
  region: ap-southeast-2
  access_key_id: AKIAJTJ7ZET3BDMLVECA
  secret_access_key: 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
kms:
  alias: s4tool
s3:
  bucket: chrisdlangton
  base_path: "{{ HOSTNAME }}/{{ USER }}"    
