---
# Prevents the creation of any AWS resources such as S3 buckets and KMS keys
safe_mode: True

aws:
  access_key_id: ABCDEF123ABCDEF123
  secret_access_key: abcdefabcdefabcdefabcdefabcdefabcdef

s3:
  bucket: bucketname
  base_path: "{{ HOSTNAME }}/{{ USER }}"